language: php

sudo: false

matrix:
  include:
    - php: 5.5
      env: PROCESS_CODECLIMATE=true
    - php: 5.6
    - php: nightly
    - php: hhvm

  allow_failures:
    - php: hhvm
    - php: nightly

before_script:
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update
  - travis_retry composer update --dev --prefer-source
  - php -v

script: ./test/bin/ci.bash summary
